title: Markos Ioannou Â· Data & Analytics
url: https://markos-ioannou.com
description: Personal website of Markos Ioannou, featuring data analytics and machine learning projects, skills, and experience.

plugins:
  - jekyll-sitemap